
export const ActionTypes = {
    GET_USERS: "GET_USERS",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    SEARCH_USER: "SEARCH_USER",
    SORT_USER: "SORT_USER"
}